package org.osmdroid;

//this file is automatically generated during the build
//when making changes, only edit ./src/main/filtered/...
//https://github.com/osmdroid/osmdroid/issues/1500
public class OsmdroidBuildInfo {

    private OsmdroidBuildInfo() {
    }

    public static final String VERSION = "6.1.20";
    public static final String BUILD_DATE = "Sun Aug 18 18:55:33 EDT 2024";
}